/*
 *
 * Product constants
 *
 */

export const PRODUCT_ADDED_TO_CART = 'app/Product/PRODUCT_ADDED_TO_CART';
export const PRODUCT_REMOVED_FROM_CART =
  'app/Product/PRODUCT_REMOVED_FROM_CART';

export const PRODUCT_WITH_VARIANT_ADDED_TO_CART = 'app/Product/PRODUCT_WITH_VARIANT_ADDED_TO_CART';
export const PRODUCT_WITH_VARIANT_REMOVED_FROM_CART = 'app/Product/PRODUCT_WITH_VARIANT_REMOVED_FROM_CART';

export const SET_PRODUCT_IN_CART = 'app/Product/SET_PRODUCT_IN_CART';
export const SET_VARIANTS_IN_PRODUCT_CART = 'app/Product/SET_VARIANTS_IN_PRODUCT_CART';
export const DELIVERY_FIELD_SELECTED = 'app/Product/DELIVERY_FIELD_SELECTED';
export const SELF_PICK_UP_FIELD_SELECTED =
  'app/Product/SELF_PICK_UP_FIELD_SELECTED';
