/*
 *
 * DetailsPage constants
 *
 */

export const CONFIGURE_BUSINESS_NAME =
  'app/DetailsPage/CONFIGURE_BUSINESS_NAME';
export const CONFIGURE_FULFILLMENT_METHOD =
  'app/DetailsPage/CONFIGURE_FULFILLMENT_METHOD';
export const CONFIGURE_FULFILLMENT_DERIVATIVES =
  'app/DetailsPage/CONFIGURE_FULFILLMENT_DERIVATIVES';
export const CONFIGURE_POSTSCRIPT = 'app/DetailsPage/CONFIGURE_POSTSCRIPT';
export const CONFIGURE_PAYMENT_METHOD =
  'app/DetailsPage/CONFIGURE_PAYMENT_METHOD';
export const RESET_ALL_FORM_EXCEPT_BUSINESS_NAME =
  'app/DetailsPage/RESET_ALL_FORM_EXCEPT_BUSINESS_NAME';
